import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAppStore } from '@/store/appStore';
export const ProgressView = ({ onBack }) => {
    const { phrases, favorites } = useAppStore();
    const stats = {
        totalPhrases: phrases.length,
        totalFavorites: favorites.size,
        totalCategories: new Set(phrases.map(p => p.category)).size,
        visiblePhrases: phrases.filter(p => p.isVisible).length
    };
    return (_jsxs("div", { className: "fixed inset-0 bg-dark-bg z-40 overflow-y-auto", children: [_jsx("div", { className: "sticky top-0 bg-dark-surface border-b border-white border-opacity-5 p-4 z-50", children: _jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("button", { onClick: onBack, className: "text-white hover:text-gray-300 transition-colors", children: "\u2190 Volver" }), _jsx("h2", { className: "text-lg font-bold text-white", children: "PROGRESO" }), _jsx("div", { className: "w-6" })] }) }), _jsxs("div", { className: "p-4 space-y-4", children: [_jsx("div", { className: "bg-dark-tertiary border border-white border-opacity-10 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-400 mb-1", children: "Total de frases" }), _jsx("p", { className: "text-3xl font-bold text-accent-listen", children: stats.totalPhrases })] }), _jsx("div", { className: "text-4xl", children: "\uD83D\uDCCB" })] }) }), _jsx("div", { className: "bg-dark-tertiary border border-white border-opacity-10 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-400 mb-1", children: "Frases visibles" }), _jsx("p", { className: "text-3xl font-bold text-accent-slow", children: stats.visiblePhrases })] }), _jsx("div", { className: "text-4xl", children: "\uD83D\uDC41\uFE0F" })] }) }), _jsx("div", { className: "bg-dark-tertiary border border-white border-opacity-10 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-400 mb-1", children: "Frases favoritas" }), _jsx("p", { className: "text-3xl font-bold text-yellow-400", children: stats.totalFavorites })] }), _jsx("div", { className: "text-4xl", children: "\u2B50" })] }) }), _jsx("div", { className: "bg-dark-tertiary border border-white border-opacity-10 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-400 mb-1", children: "Categor\u00EDas" }), _jsx("p", { className: "text-3xl font-bold text-accent-lips", children: stats.totalCategories })] }), _jsx("div", { className: "text-4xl", children: "\uD83C\uDFF7\uFE0F" })] }) }), _jsxs("div", { className: "bg-dark-tertiary border border-white border-opacity-10 rounded-lg p-4", children: [_jsx("h3", { className: "font-bold text-white mb-3", children: "Categor\u00EDas utilizadas" }), _jsx("div", { className: "space-y-2", children: Array.from(new Set(phrases.map(p => p.category))).map(category => {
                                    const count = phrases.filter(p => p.category === category).length;
                                    return (_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm text-gray-300", children: category }), _jsx("span", { className: "text-sm font-semibold text-accent-listen", children: count })] }, category));
                                }) })] }), _jsx("div", { className: "bg-blue-900 bg-opacity-20 border border-blue-500 border-opacity-50 rounded-lg p-4 text-center", children: _jsx("p", { className: "text-xs text-blue-300", children: "\uD83D\uDCA1 Usa el gestor de frases para agregar m\u00E1s contenido y expandir la biblioteca" }) })] })] }));
};
